# Site
name: 'The WDevops'
description: 'Free Developer Resources and updates for Tech Startups to build their MVP or prototypes. Promoting awesome work by awesome people. Share and Grow...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'wdevops'
email: 'me@sangram.pro'
# mailchimp-list: 'https://Ambivert.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-amp
 
authors:
    Sangram:
      name:           Sangram
      site:           https://www.sangram.pro
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Sangram Chavan, Entrepreneur and author of this website."
      email:          me@sangram.pro
      twitter:        https://twitter.com/sangram_pro

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sangram
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

redirect_from:
  permalink: /tag/
  redirect_to: /
  permalink: /free-high-quality-photos/
  redirect_to: /
  permalink: /free-for-developers/
  redirect_to: /categories.html#developer/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
