# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Wdevops
email: me@sangram.pro
description: >
  Relevent to Tech! Share and Grow...
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wdevops.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Sangram Chavan'
bio: >
  Hi, I am Sangram Chavan, Entrepreneur and author of this website.
author_image: "/assets/images/author.jpg"
twitter_username: sangram_pro
github_username:  SangramChavan

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
